proxy-providers:
  fool:
    type: http
    url: "http://fool.azurewebsites.net/get?limit=10&format=clash&cc=SG,ID&cdn=104.22.25.131&network=ws&arg=xudp,key:value&mode=cdn&pass=qk4ndl7g"
    interval: 15
    path: ./provider.yaml
    health-check:
      enable: true
      interval: 240
      url: https://cp.cloudflare.com/generate_204
      proxies:
proxy-groups:
  - name: SIMASTER-MAGISK-AUTO
    type: url-test
    use:
      - fool
rule-providers:
  Game:
    type: http
    behavior: domain
    path: ./confs/rule-game.yaml
    url: https://raw.githubusercontent.com/clashz3ro/AUTO-CFA/main/rule-game.yaml
    interval: 60
  Sosmed:
    type: http
    behavior: domain
    path: ./confs/rule-sosmed.yaml
    url: https://raw.githubusercontent.com/clashz3ro/AUTO-CFA/main/rule-sosmed.yaml
    interval: 60
  Stream:
    type: http
    behavior: domain
    path: ./confs/rule-stream.yaml
    url: https://raw.githubusercontent.com/clashz3ro/AUTO-CFA/main/rule-stream.yaml
    interval: 60
  Olshop:
    type: http
    behavior: domain
    path: ./confs/rule-olshop.yaml
    url: https://raw.githubusercontent.com/clashz3ro/AUTO-CFA/main/rule-olshop.yaml
    interval: 60
  Bank:
    type: http
    behavior: domain
    path: ./confs/rule-bank.yaml
    url: https://raw.githubusercontent.com/clashz3ro/AUTO-CFA/main/rule-bank.yaml
    interval: 60
  Whatsapp:
    type: http
    behavior: domain
    path: ./confs/rule-whatsapp.yaml
    url: https://raw.githubusercontent.com/clashz3ro/AUTO-CFA/main/rule-whatsapp.yaml
    interval: 60
  AdBlock:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_basicads.yaml
    path: "./confs/rule_basicads.yaml"
    interval: 60
  Personalads:
    type: http
    behavior: domain
    url: https://raw.githubusercontent.com/malikshi/open_clash/main/rule_provider/rule_personalads.yaml
    path: "./confs/rule_personalads.yaml"
    interval: 86400
script:
  code: |
    def main(ctx, metadata):
        ruleset_action = {"Game": "GAMING",
            "Sosmed": "SIMASTER-MAGISK-AUTO",
            "Stream": "SIMASTER-MAGISK-AUTO",
            "Olshop": "SIMASTER-MAGISK-AUTO",
            "Bank": "SIMASTER-MAGISK-AUTO",
            "Whatsapp": "WHATSAPP",
          }

        port = int(metadata["dst_port"])

        if metadata["network"] == "UDP":
            if port == "21,22,23,53,80,443,8443":
                ctx.log('[Script] matched QUIC traffic use SIMASTER-MAGISK-AUTO')
                return "SIMASTER-MAGISK-AUTO"

        if metadata["dst_ip"] == "":
            metadata["dst_ip"] = ctx.resolve_ip(metadata["host"])

        port_list = [21, 22, 23, 53, 80, 81, 123, 443, 853, 5353, 8000, 8008, 8080, 8081, 8090, 8443, 8888, 9993]
        if port not in port_list:
            ctx.log('[Script] not common port use GAMING')
            return "GAMING"

        if metadata["dst_ip"] == "":
            return "DIRECT"

        for ruleset in ruleset_action:
            if ctx.rule_providers[ruleset].match(metadata):
                return ruleset_action[ruleset]

        code = ctx.geoip(metadata["dst_ip"])
        if code == "ID":
            ctx.log('[Script] Geoip ID')
            return "SIMASTER-MAGISK-AUTO"

        ctx.log('[Script] SIMASTER-AUTO')
        return "SIMASTER-MAGISK-AUTO"
rules:
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- DOMAIN-SUFFIX,googlesyndication.com,SIMASTER-MAGISK-AUTO
- RULE-SET,Game,GAMING
- RULE-SET,Sosmed,SIMASTER-MAGISK-AUTO
- RULE-SET,Stream,SIMASTER-MAGISK-AUTO
- RULE-SET,Olshop,SIMASTER-MAGISK-AUTO
- RULE-SET,Bank,SIMASTER-MAGISK-AUTO
- RULE-SET,Whatsapp,WHATSAPP
- RULE-SET,AdBlock,AdBlock
- RULE-SET,Personalads,AdBlock
- GEOIP,ID,SIMASTER-MAGISK-AUTO
- MATCH,SIMASTER-MAGISK-AUTO
